// <auto-generated />
using System;
using HentaiPages.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HentaiPages.Migrations
{
    [DbContext(typeof(HentaiDbContext))]
    [Migration("20211225222114_hashingIndex")]
    partial class hashingIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("HentaiPages.Database.Tables.Image", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<bool>("Favourite")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("Hash");

                    b.HasIndex("ImageId", "UploadDate");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("HentaiPages.Database.Tables.Tags", b =>
                {
                    b.Property<int>("TagsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("TagsId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HentaiPages.Database.Tables.TagsImages", b =>
                {
                    b.Property<long>("ImageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("TagsImages");
                });

            modelBuilder.Entity("HentaiPages.Database.Tables.TagsImages", b =>
                {
                    b.HasOne("HentaiPages.Database.Tables.Image", "Image")
                        .WithMany("Tags")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HentaiPages.Database.Tables.Tags", "Tag")
                        .WithMany("Images")
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
